import moment from 'moment';
import { Plant } from '../Models/plant/plant.model';

const ex1 = {
  plant_name: 'Menta',
  id: 'maneta',
  plant_type: {
    name: 'Aromatica',
  },
  harvest_date: '15-01-2023',
  planting_date: '14-10-2022',
  last_harvest: null,
  assigned_color: 'RED2',
  last_watering: null,
  last_prune: null,
  last_fertilization: null,
  last_application_of_insecticide: null,
  last_application_of_fungicide: null,
  watered_schedule: {
    name: 'Todos los dias',
    init_date: '2022-11-17T00:40:04.399Z',
    step_repeat: 1,
    next_event: '19-11-2022',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  prune_schedule: {
    name: 'Cada semana',
    init_date: '2022-11-17T00:40:04.400Z',
    step_repeat: 7,
    next_event: '2022-11-19T00:40:04.400Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  fertilization_schedule: {
    name: 'Nunca',
    init_date: null,
    step_repeat: null,
    next_event: null,
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  insecticide_schedule: {
    name: 'Cada semana',
    init_date: '2022-11-17T00:40:04.400Z',
    step_repeat: 7,
    next_event: '2022-11-19T00:40:04.400Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  fungal_schedule: null,
};

const ex2 = {
  plant_name: 'Lavanda',
  id: 'lavanda',
  plant_type: {
    name: 'Aromatica',
  },
  harvest_date: null,
  planting_date: null,
  last_harvest: null,
  assigned_color: 'RED2',
  last_watering: '2022-11-18T13:21:08-03:00',
  last_prune: '2022-11-18T13:18:49-03:00',
  last_fertilization: '2022-11-17T21:41:36-03:00',
  last_application_of_insecticide: null,
  last_application_of_fungicide: null,
  watered_schedule: {
    name: 'Todos los dias',
    init_date: '2022-11-18T00:40:04.399Z',
    step_repeat: 1,
    next_event: '2022-11-20T00:40:04.399Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  prune_schedule: {
    name: 'Cada semana',
    init_date: '2022-11-18T00:40:04.400Z',
    step_repeat: 7,
    next_event: '2022-11-25T00:40:04.400Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  fertilization_schedule: {
    name: 'Nunca',
    init_date: null,
    step_repeat: null,
    next_event: null,
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  insecticide_schedule: null,
  fungal_schedule: null,
};

export const testGarden = [new Plant(ex1), new Plant(ex2)];
