import moment from 'moment';
import { Plant } from '../Models/plant/plant.model';

const ex1 = {
  plant_name: 'Menta',
  id: 'maneta',
  plant_type: {
    name: 'Aromatica',
  },
  harvest_date: '15-01-2023',
  planting_date: '14-10-2022',
  last_harvest: null,
  assigned_color: 'RED2',
  last_watering: null,
  last_prune: null,
  last_fertilization: null,
  last_application_of_insecticide: null,
  last_application_of_fungicide: null,
  watered_schedule: {
    name: 'Todos los dias',
    init_date: '2022-11-17T00:40:04.399Z',
    step_repeat: 1,
    next_event: '19-11-2022',
    scheduled: true,
    notificate: false,
    extra_data: null,
  },
  prune_schedule: {
    name: 'Cada semana',
    init_date: '2022-11-17T00:40:04.400Z',
    step_repeat: 7,
    next_event: '2022-11-19T00:40:04.400Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  fertilization_schedule: {
    name: 'Nunca',
    init_date: null,
    step_repeat: null,
    next_event: null,
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  insecticide_schedule: {
    name: 'Cada semana',
    init_date: '2022-11-17T00:40:04.400Z',
    step_repeat: 7,
    next_event: '2022-11-19T00:40:04.400Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  fungal_schedule: null,
};

const ex2 = {
  plant_name: 'Lavanda',
  id: 'lavanda',
  plant_type: {
    name: 'Aromatica',
  },
  harvest_date: null,
  planting_date: null,
  last_harvest: null,
  assigned_color: 'RED2',
  last_watering: '2022-11-18T13:21:08-03:00',
  last_prune: '2022-11-18T13:18:49-03:00',
  last_fertilization: '2022-11-17T21:41:36-03:00',
  last_application_of_insecticide: null,
  last_application_of_fungicide: null,
  watered_schedule: {
    name: 'Todos los dias',
    init_date: '2022-11-18T00:40:04.399Z',
    step_repeat: 1,
    next_event: '2022-11-20T00:40:04.399Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  prune_schedule: {
    name: 'Cada semana',
    init_date: '2022-11-18T00:40:04.400Z',
    step_repeat: 7,
    next_event: '2022-11-25T00:40:04.400Z',
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  fertilization_schedule: {
    name: 'Nunca',
    init_date: null,
    step_repeat: null,
    next_event: null,
    final_date: null,
    notificate: false,
    extra_data: null,
  },
  insecticide_schedule: null,
  fungal_schedule: null,
};

const ex3 = {
  plant_name: 'florini',
  id: 'florini',
  plant_type: 'FLOWER',
  harvest_date: '2022-11-24T14:41:43.332Z',
  planting_date: '2022-11-24T14:41:43.332Z',
  last_harvest: null,
  assigned_color: 'RED2',
  last_watering: null,
  last_prune: null,
  last_fertilization: null,
  last_application_of_insecticide: null,
  last_application_of_fungicide: null,
  watered_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-24T14:41:47.864Z',
    step_repeat: 1,
    step_format: 'DAY',
    days_to_repeat: [],
    next_event: '2022-11-24T14:41:47.864Z',
    scheduled: true,
    notificate: false,
    extra_data: null,
    end_date: '2022-11-24T14:41:47.864Z',
    last_execution: null,
    end_format: null,
    repeats: 0,

    month_data: {
      day: null,
      handler: null,
    },
    end_handler: 'BY_DATE',
    step_repeat_for_end: '1',
  },
  prune_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-18T14:41:47.864Z',
    step_repeat: 1,
    step_format: 'WEEK',
    days_to_repeat: [0, 3, 4, 6],
    next_event: '2022-11-20T14:41:47.864Z',
    scheduled: true,
    notificate: false,
    extra_data: null,
    end_date: '2022-11-25T14:41:47.864Z',
    last_execution: '2022-11-17T19:25:15.944Z',
    end_format: null,
    repeats: 1,
    month_data: {
      day: null,
      handler: null,
    },
    end_handler: 'BY_DATE',
    step_repeat_for_end: '2',
  },
  fertilization_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-24T14:59:31.000Z',
    step_repeat: 1,
    step_format: 'MONTH',
    days_to_repeat: [],
    next_event: '2022-11-24T14:59:31.000Z',
    scheduled: true,
    notificate: false,
    extra_data: null,
    end_date: '2022-12-24T14:59:31.805Z',
    last_execution: null,
    end_format: null,
    repeats: 0,
    month_data: { day: 1, handler: 'FIRST' },
    end_handler: 'NEVER', // <= 'NEVER, BY_STEPS, BY_DATE
    step_repeat_for_end: '4',
  },
  insecticide_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-24T14:42:02.096Z',
    step_repeat: 1,
    step_format: 'MONTH',
    days_to_repeat: [],
    next_event: '',
    scheduled: true,
    notificate: false,
    extra_data: null,
    last_execution: null,
    end_date: '2022-12-24T14:42:02.096Z',
    end_format: null,
    repeats: 0,

    month_data: { day: 4, handler: 'LAST' },
    end_handler: 'NEVER',
  },
  fungal_schedule: null,
};

const ex4 = {
  plant_name: 'TEST',
  id: 'test',
  plant_type: 'CACTUS',
  harvest_date: '2022-11-25T21:15:22.633Z',
  planting_date: '2022-11-05T21:15:22.000Z',
  last_harvest: null,
  assigned_color: 'RED2',
  last_watering: null,
  last_prune: null,
  last_fertilization: null,
  last_application_of_insecticide: null,
  last_application_of_fungicide: null,
  watered_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-25T21:15:29.305Z',
    step_repeat: 1,
    step_format: 'DAY',
    days_to_repeat: [],
    next_event: '',
    scheduled: true,
    last_execution: null,
    notificate: false,
    extra_data: null,
    end_date: '2022-12-25T21:15:29.305Z',
    end_format: null,
    repeats: 0,
    repeats_to_end: 1,
    month_data: {
      day: null,
      handler: null,
    },
    end_handler: null,
  },
  prune_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-25T21:15:32.632Z',
    step_repeat: '1',
    step_format: 'MONTH',
    days_to_repeat: [],
    next_event: '',
    scheduled: true,
    last_execution: null,
    notificate: false,
    extra_data: null,
    end_date: '2022-12-25T21:15:32.632Z',
    end_format: null,
    repeats: 0,
    repeats_to_end: 1,
    month_data: '{"day":5,"handler":"FOURTH"}',
    end_handler: null,
  },
  fertilization_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-25T21:15:47.057Z',
    step_repeat: 1,
    step_format: 'DAY',
    days_to_repeat: [],
    next_event: '',
    scheduled: true,
    last_execution: null,
    notificate: false,
    extra_data: null,
    end_date: '2022-12-25T21:15:47.057Z',
    end_format: null,
    repeats: 0,
    repeats_to_end: 1,
    month_data: {
      day: null,
      handler: null,
    },
    end_handler: null,
  },
  insecticide_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-29T21:15:42.000Z',
    step_repeat: 1,
    step_format: 'WEEK',
    days_to_repeat: [1, 3, 6],
    next_event: '',
    scheduled: true,
    last_execution: null,
    notificate: false,
    extra_data: null,
    end_date: '2022-12-25T21:15:42.979Z',
    end_format: null,
    repeats: 0,
    repeats_to_end: 1,
    month_data: {
      day: null,
      handler: null,
    },
    end_handler: null,
  },
  fungal_schedule: {
    name: 'PERSONALIZED',
    init_date: '2022-11-25T21:15:50.444Z',
    step_repeat: 1,
    step_format: 'MONTH',
    days_to_repeat: [],
    next_event: '',
    scheduled: true,
    last_execution: null,
    notificate: false,
    extra_data: null,
    end_date: '2022-12-25T21:15:50.444Z',
    end_format: null,
    repeats: 0,
    repeats_to_end: 1,
    month_data: '{"day":5,"handler":"LAST"}',
    end_handler: null,
  },
};
export const testGarden = [
  new Plant(ex1),
  new Plant(ex2),
  new Plant(ex3),
  new Plant(ex4),
];
